# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e6f11d50b5509c1264b6ddd338017271b0ff158b5cee8f431a9f098d0398ed0d564e84935e33bae3e47a44dc8911d09aedc7346fb8e9a216a23a494cba34ac

test:
  secret_key_base: e56bff1c82a2ee97d0307b84b72d0b07ac7c1d23d2c6f7a7e180db3551a983eebb23884d33be2b30f5eecbc306b989beb29630748e6232ebe4c13889212854a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
